controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    arm_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
    interface_name: position

gripper_controller:
  ros__parameters:
    joints:
      - joint_4
    interface_name: position
